import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { Container,Row,Col,Navbar,Nav,NavDropdown } from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>دکوراسیون شادمان - رمکان</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Lalezar&display=swap" rel="stylesheet"/> 
      </Head>
      <main  dir='rtl'>
        <Container className={styles.min} fluid>
          <Row>
            <Col>
            <Navbar fixed='True' expand="lg" className={styles.nvab}>
      <Container>
        <Navbar.Brand href="#home" className={styles.pvc}>دکوراسیون شادمان - رمکان</Navbar.Brand>
        <Navbar.Toggle aria-controls="basic-navbar-nav" />
        <Navbar.Collapse id="basic-navbar-nav">
          <Nav className="me-auto">
            <Nav.Link href="#home" className={styles.home} >صفحه اصلی</Nav.Link>
            <Nav.Link href="#UPVC" className={styles.home}>طرح های UPVC</Nav.Link>
            <Nav.Link href="#About" className={styles.home}>ارتباط با ما</Nav.Link>
           
          </Nav>
        </Navbar.Collapse>
      </Container>
    </Navbar>
            </Col>
          </Row>
        </Container>
      
       <Container className={styles.bg1} fluid>
        <Row>
          <Col sm={5}>
          <img className={styles.imgsh} width={200} src='https://lluminare.com/assets/images/resources/8/thermo-front-0.gif'/>
          </Col>
          <Col sm={2}/>
          <Col sm={4}>
          <p className={styles.shademanp}>
    تولیدی درب و پنجره UPVC نوین ترک
    فروش و نصب PVC
    طراحی و ساخت و اجرای انواع سایبان PVC

فروش بصورت نقد و اقساط فقط با چک</p>
          </Col>
        </Row>
       </Container>

      </main>
    </>
  )
}
