import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { Container, Row, Col, Navbar, Nav, NavDropdown } from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>دکوراسیون شادمان - رمکان</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://www.pngfind.com/pngs/m/57-579183_upvc-openable-windows-hd-png-download.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Lalezar&display=swap" rel="stylesheet" />
      </Head>
      <main dir='rtl'>
        <Container className={styles.min} fluid>
          <Row>
            <Col>
              <Navbar expand="lg" className={styles.nvab}>
                <Container>
                  <Navbar.Brand href="#home" className={styles.pvc}>
                    <p className={styles.dekor}>دکوراسیون شادمان - رمکان</p>
                  </Navbar.Brand>
                  <Navbar.Brand href="#home" className={styles.pvc}>
                    <img width={100} src='icon.png' />
                  </Navbar.Brand>
                  <Navbar.Toggle aria-controls="basic-navbar-nav" />
                  <Navbar.Collapse id="basic-navbar-nav">
                    <Nav className="me-auto">
                      <Nav.Link href="#home" className={styles.home} >صفحه اصلی</Nav.Link>
                      <Nav.Link href="#UPVC" className={styles.home}>طرح های UPVC</Nav.Link>
                      <Nav.Link href="#About" className={styles.home}>ارتباط با ما</Nav.Link>

                    </Nav>
                  </Navbar.Collapse>
                </Container>
              </Navbar>
            </Col>
          </Row>
        </Container>

        <Container className={styles.bg1} fluid>
          <Row>
            <Col sm={5}>
              <img className={styles.imgsh} width={150} src='https://lluminare.com/assets/images/resources/8/thermo-front-0.gif' />
            </Col>
            <Col sm={2} />
            <Col sm={4}>
              <p className={styles.shademanp}>
                تولیدی درب و پنجره UPVC نوین ترک
                فروش و نصب PVC
                طراحی یا ساخت و اجرای انواع سایبان PVC
              </p>

              <p>فروش بصورت نقد و اقساط فقط با چک</p>
            </Col>
          </Row>
        </Container>

        <Container >

          <Row>



            <Col sm={5}>
              <Container>


                <Row className={styles.upvcimg}>
                  <Col sm={12}>
                    <img width={60} src='/icon.png' />
                  </Col>
                  <Col >
                    <Link href={"/upvc/i1.jpg"} target={"#"}>
                      <img className={styles.imgs} width={150} src='/upvc/i1.jpg' />

                    </Link>
                  </Col>
                  <Col >
                    <p className={styles.pp}>نمونه اجرا شده برای مشتری عزیز
                      با طرح دکوراتیو طلایی</p>

                    <hr />

                    <p className={styles.code}>کد 10</p>
                  </Col>


                </Row>
              </Container>
            </Col>




            <Col sm={4}>
              <Container>


                <Row className={styles.upvcimg}>
                  <Col sm={12}>
                    <img width={60} src='/icon.png' />
                  </Col>
                  <Col >
                    <Link href={"/upvc/i2.jpg"} target={"#"}>
                      <img className={styles.imgs} width={150} src='/upvc/i2.jpg' />

                    </Link>
                  </Col>
                  <Col >
                    <p className={styles.pp}>
                    نمونه پنجره با دکوراتیو خطی طلایی
                    </p>

                    <hr />

                    <p className={styles.code}>کد 20</p>
                  </Col>


                </Row>
              </Container>
            </Col>







            <Col sm={8}>
              <Container>


                <Row className={styles.upvcimg}>
                  <Col sm={12}>
                    <img width={60} src='/icon.png' />
                  </Col>
                  <Col >
                    <Link href={"/upvc/i3.jpg"} target={"#"}>
                      <img className={styles.imgs} width={150} src='/upvc/i3.jpg' />

                    </Link>
                  </Col>
                  <Col >
                    <p className={styles.pp}>
                    پنجره های طرح هلالی

                    </p>

                    <hr />

                    <p className={styles.code}>کد 30</p>
                  </Col>


                </Row>
              </Container>
            </Col>


            <Col sm={3}>
              <Container>


                <Row className={styles.upvcimg}>
                  <Col sm={12}>
                    <img width={60} src='/icon.png' />
                  </Col>
                  <Col >
                    <Link href={"/upvc/i4.jpg"} target={"#"}>
                      <img className={styles.imgs} width={150} src='/upvc/i4.jpg' />

                    </Link>
                  </Col>
                  <Col >
                    <p className={styles.pp}>
                    قابل اجرا برای درب سرویس.حمام.راهرو.ورودی و.....با دکوراتیو شیشه طلایی و سفید
                    </p>

                    <hr />

                    <p className={styles.code}>کد 40</p>
                  </Col>


                </Row>
              </Container>
            </Col>





            <Col sm={5}>
              <Container>


                <Row className={styles.upvcimg}>
                  <Col sm={12}>
                    <img width={60} src='/icon.png' />
                  </Col>
                  <Col >
                    <Link href={"/upvc/i5.jpg"} target={"#"}>
                      <img className={styles.imgs} width={150} src='/upvc/i5.jpg' />

                    </Link>
                  </Col>
                  <Col >
                    <p className={styles.pp}>
                    اجرای درب و پنجره با دکوراتیو طرح دار سفید و طلایی
                    </p>

                    <hr />

                    <p className={styles.code}>کد 50</p>
                  </Col>


                </Row>
              </Container>
            </Col>







            <Col sm={6}>
              <Container>


                <Row className={styles.upvcimg}>
                  <Col sm={12}>
                    <img width={60} src='/icon.png' />
                  </Col>
                  <Col >
                    <Link href={"/upvc/i6.jpg"} target={"#"}>
                      <img className={styles.imgs} width={150} src='/upvc/i6.jpg' />

                    </Link>
                  </Col>
                  <Col >
                    <p className={styles.pp}>
                    پنل دکوراتیو ساخت ترکیه..قابل اجرا برای درب سرویس.حمام.راهرو.ورودی و.....با عرض 90 سانت ب بالا
                    </p>

                    <hr />

                    <p className={styles.code}>کد 60</p>
                  </Col>


                </Row>
              </Container>
            </Col>






            <Col sm={4}>
              <Container>


                <Row className={styles.upvcimg}>
                  <Col sm={12}>
                    <img width={60} src='/icon.png' />
                  </Col>
                  <Col >
                    <Link href={"/upvc/i7.jpg"} target={"#"}>
                      <img className={styles.imgs} width={150} src='/upvc/i7.jpg' />

                    </Link>
                  </Col>
                  <Col >
                    <p className={styles.pp}>
                    نمونه کار شیشه دکوراتیو طرحدار قابل اجرا با آیینه
                    </p>

                    <hr />

                    <p className={styles.code}>کد 70</p>
                  </Col>


                </Row>
              </Container>
            </Col>










          </Row>

        </Container>

      </main>
    </>
  )
}
