import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { Container,Row,Col,Navbar,Nav,NavDropdown } from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>دکوراسیون شادمان</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main  dir='rtl'>
        <Container className={styles.min}>
          <Row>
            <Col>
            <Navbar  expand="lg" className={styles.nvab}>
      <Container>
        <Navbar.Brand href="#home">دکوراسیون شادمان</Navbar.Brand>
        <Navbar.Toggle aria-controls="basic-navbar-nav" />
        <Navbar.Collapse id="basic-navbar-nav">
          <Nav className="me-auto">
            <Nav.Link href="#home">صفحه اصلی</Nav.Link>
            <Nav.Link href="#link">طرح های UPVC</Nav.Link>
            <Nav.Link href="#link">ارتباط با ما</Nav.Link>
           
          </Nav>
        </Navbar.Collapse>
      </Container>
    </Navbar>
            </Col>
          </Row>
        </Container>
      
       

        <p className={styles.pp}>Hi</p>
      </main>
    </>
  )
}
